default_language_version:
    python: python3.10.8
repos:
    - repo: local
      hooks:
          - id: pylint
              name: pylint
              entry: pylint
              args: ["--rcfile=.pylintrc"]
              language: system
              types: [python]
              require_serial: true
          - id: black
              name: black
              entry: black
              language: system
          - id: isort
              name: isort
              entry: isort
              args: ["--profile", "black"]
              language: system