default_language_version:
  python: python3.9.6
repos:
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        args: ["--rcfile=.pylintrc"]
        language: system
        types: [python]
        require_serial: true
      - id: black
        name: black
        entry: black
        language: system
        args: [.]
        pass_filenames: false
        always_run: true
      - id: isort
        name: isort
        entry: isort
        args: ["--profile", "black"]
        language: system
